--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, 
--     LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PROV_GROUP_ID, 
--     SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, 
--     ACTION_CODE, PROV_DATA_TYPE, ORDER_PROD_SERVICE
--  FROM TPT.TX_CAT_PROD_SERVICE;
--
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '112', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'BIT', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '115', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'BIT', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '349', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '350', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '351', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '352', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '353', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '5', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'GOLD', '92', 'TPT_MCH', TO_TIMESTAMP('9/30/2024 2:03:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'BIT', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '112', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:07.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'BIT', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '115', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:07.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'BIT', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '30', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:07.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'BIT', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '349', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:08.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '350', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:08.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '351', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:08.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
Insert into TX_CAT_PROD_SERVICE
   (SERVICE_REGION_ID, SERVICE_PRODUCT_ID, PROV_DATA, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
    PROV_GROUP_ID, SERVICE_TYPE, TECNO_ID, CLASIFICATION_NODE, ACTION_CODE, 
    PROV_DATA_TYPE, ORDER_PROD_SERVICE)
 Values
   (0, 'SILVER', '5', 'TPT_MCH', TO_TIMESTAMP('10/2/2024 2:27:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 
    'G1', 'Video', 'SYNAMEDIA', NULL, NULL, 
    'SERVICE_ID', 0);
COMMIT;
