--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, TECNO_ID, TECNO_ID_DESC, LAST_MODIFIED_USERID, 
--     LAST_MODIFIED_DATE, PROV_GROUP_ID
--  FROM TPT.TX_CAT_TECNO;
--
Insert into TX_CAT_TECNO
   (TECNO_ID, TECNO_ID_DESC, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PROV_GROUP_ID)
 Values
   ('SYNAMEDIA', 'APROV PRODUCTOS SKY', 'TPT', TO_TIMESTAMP('9/18/2024 6:08:04.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'G1');
COMMIT;
