--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, 
--     PARAM_LABEL, PARAM_VALUE, PARAM_TYPE, 
--     PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, 
--     PARAM_PATH_TO
--  FROM TPT.TX_CSDL_PARAM;
--
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_GET_INFORMATION', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 3, 'DEVICE_TYPE', 'SLAVE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 4, 'EXP_DATE', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 5, 'MASTER_CARD_ID', 'Card Id Master', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 6, 'MASTER_SLAVE_CNT', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (SLAVE)', 1, 7, 'SLAVE_PREMISE_ID', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_HR', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_HR', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_HR', 1, 3, 'SERVICE_TYPE[1]', 'Arreglo de paquetes', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_HR', 1, 4, 'EXPIRY_DATE[1]', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_HR', 1, 5, 'SERVICE_ID[1]', 'Arreglo de paquetes', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:13.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_HR', 1, 6, 'TAPING_AUTH[1]', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_EMAIL_WEL', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_EMAIL_WEL', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_EMAIL_WEL', 1, 3, 'ACCOUNT_NBR', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:Customer/te:CustomerAccount[tc:EntityID/tc:Id=/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:AccountReference[tc:ClasificationCode="Service"]/tc:Id]/te:AccountNumber/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_GET_INFORMATION', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_GET_INFORMATION', 1, 3, 'INFO_TYPE', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER', 1, 3, 'ZIP_CODE', NULL, 
    'V', '/ti:CreateOrderIM/ti:Body/ti:Order/te:Customer/te:CustomerAddress[1]/te:Property/tc:Postcode/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_RECEIVER_ID', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:09.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_RECEIVER_ID', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_RECEIVER_ID', 1, 3, 'RECEIVER_ID', NULL, 
    'V', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 3, 'START_SERVICE_ID', '5', 
    'F', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 4, 'END_SERVICE_ID', '5', 
    'F', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 5, 'SERVICE_TYPE[1]', 'Arreglo de paquetes', 
    'E', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 6, 'SERVICE_ID', 'Arreglo de paquetes', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 7, 'EXPIRY_DATE[1]', NULL, 
    'E', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_MULTI_AUTH', 1, 8, 'TAPING_AUTH[1]', NULL, 
    'E', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:10.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_AUTH', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_AUTH', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_AUTH', 1, 3, 'EXPIRY_DATE[1]', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_AUTH', 1, 4, 'SERVICE_ID[1]', 'Arreglo de paquetes', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_AUTH', 1, 5, 'SERVICE_TYPE[1]', 'Arreglo de paquetes', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SERVICE_AUTH', 1, 6, 'TAPING_AUTH[1]', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_CLEAR_RANGE_REGION_BITS', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_CLEAR_RANGE_REGION_BITS', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_CLEAR_RANGE_REGION_BITS', 1, 3, 'ACCOUNT_NBR', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:Customer/te:CustomerAccount[tc:EntityID/tc:Id=/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:AccountReference[tc:ClasificationCode="Service"]/tc:Id]/te:AccountNumber/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:11.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SET_CLEAR_RANGE_REGION_BITS', 1, 4, 'RANGE_REGION_BITS.NAME1', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (MASTER)', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (MASTER)', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (MASTER)', 1, 3, 'DEVICE_TYPE', 'MASTER', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (MASTER)', 1, 4, 'EXP_DATE', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_ACT_HIERARCHY_REGEN (MASTER)', 1, 5, 'MASTER_SLAVE_CNT', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:12.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_HOUSEHOLD', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_HOUSEHOLD', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_HOUSEHOLD', 1, 3, 'HOUSEHOLD_ID', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_HOUSEHOLD', 1, 4, 'NUMBEROFBOXES', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_HOUSEHOLD', 1, 5, 'RID.NUMBER1', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 2, 'BCK_TOLERANCE', '0', 
    'F', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 3, 'CALL_BCK_AVAL', 'N', 
    'F', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 4, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 5, 'FRD_TOLERANCE', '0', 
    'F', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 6, 'REQ_CALL_BCK_DOM', '0', 
    'F', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_CREATE_SUBSCRIBER_REAUTH', 1, 7, 'ZIP_CODE', NULL, 
    'V', '/ti:CreateOrderIM/ti:Body/ti:Order/te:Customer/te:CustomerAddress[1]/te:Property/tc:Postcode/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_UPDATE_HOUSEHOLD', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_UPDATE_HOUSEHOLD', 1, 2, 'HOUSEHOLD_ID', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_UPDATE_HOUSEHOLD', 1, 3, 'NUMBEROFBOXES', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_UPDATE_HOUSEHOLD', 1, 4, 'RID.NUMBER1', NULL, 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:16.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_DELETE_SUBSCRIBER', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'C', NULL, 'TPT', TO_TIMESTAMP('9/17/2024 9:36:16.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_DELETE_SUBSCRIBER', 1, 2, 'CARD_ID', NULL, 
    'V', '/ti:CreateProvisioningOrderIM/ti:Body/ti:ProvisioningOrder/te:OrderItems/te:OrderItem[te:ServiceInfo/te:TypeCode="SI" or te:ServiceInfo/te:TypeCode="SSI"]/te:EquipmentInfo[1]/te:SerialNumber/tc:Id/text()', 'TPT', TO_TIMESTAMP('9/17/2024 9:36:16.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'NE_ID_SYNA', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'CARD_ID', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'CONNECTION_ID[1] ', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:14.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'COUNTRY_BIT.NAME1', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'DATE_TIME ', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'EMMG_DELETION_DATE', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'FLAG_ENCRYPT ', 'N_SYNAMEDIA-SMSEMMG_12-1_NE', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'MESSAGES[1].MESSAGE1', 'CC!CLEA^!^PREPARA LAS MALETAS! FINHCLEAPARTICIPA POR UN VIAJE A SUPERWFINNINTENDO WORLD', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'MESSAGES[1].MESSAGE2', 'EN UNIVERSAL WFINSTUDIOS HOLLYWOOD, CONTRATA WFINUNIVERSAL+ MARCA AL 554000712', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'MESSAGES[1].MESSAGE3', '2WFINVIGENCIA 14ENE24WFIN', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
Insert into TX_CSDL_PARAM
   (CSDL_NAME, CSDL_SEQ_NO, PARAM_SEQ_NO, PARAM_LABEL, PARAM_VALUE, 
    PARAM_TYPE, PARAM_PATH, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, PARAM_PATH_TO)
 Values
   ('C_SYNAMEDIA-SMSEMMG_12-1_SEND_BMAIL', 1, 1, 'MESSAGEID', 'BB57', 
    'F', NULL, 'TPT', TO_TIMESTAMP('11/14/2024 12:28:15.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), NULL);
COMMIT;
