--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, EQUIP_TYPE_CD, EQUIP_TYPE_DESC, LAST_MODIFIED_USERID, 
--     LAST_MODIFIED_DATE, ASAP_TYPE_CD, NETWORK_INTERFACE_DEVICE, 
--     FDA_TYPE_CD, PROVISIONING_FAMILY, VOD_ENABLED, 
--     FEATURE1, FEATURE2, TECHNOLOGY_GROUP
--  FROM TPT.TX_CAT_EQUIP_TYPE
--  ORDER BY 5 DESC NULLS LAST;
--
Insert into TX_CAT_EQUIP_TYPE
   (EQUIP_TYPE_CD, EQUIP_TYPE_DESC, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, ASAP_TYPE_CD, 
    NETWORK_INTERFACE_DEVICE, FDA_TYPE_CD, PROVISIONING_FAMILY, VOD_ENABLED, FEATURE1, 
    FEATURE2, TECHNOLOGY_GROUP)
 Values
   ('DUMMY_DTH_HMC', 'DUMMY_DTH_HMC', 'TPT', TO_TIMESTAMP('10/15/2024 5:30:22.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'DVB', 
    'HLS', 'DVB', 'HYBRID', NULL, 'ZTE B866V2', 
    'ZTE B866V2', 'DTH-HMC');
Insert into TX_CAT_EQUIP_TYPE
   (EQUIP_TYPE_CD, EQUIP_TYPE_DESC, LAST_MODIFIED_USERID, LAST_MODIFIED_DATE, ASAP_TYPE_CD, 
    NETWORK_INTERFACE_DEVICE, FDA_TYPE_CD, PROVISIONING_FAMILY, VOD_ENABLED, FEATURE1, 
    FEATURE2, TECHNOLOGY_GROUP)
 Values
   ('DUMMY_DTH', 'DUMMY_DTH', 'TPT', TO_TIMESTAMP('10/15/2024 5:30:22.000000 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'), 'DVB', 
    'HLS', 'DVB', 'HYBRID', NULL, 'ZTE B866V2', 
    'ZTE B866V2', 'DTH');
COMMIT;
